# Generated by Django 3.2.7 on 2021-09-16 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 15, 34, 14, 992206)),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
