# Generated by Django 3.2.7 on 2021-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('designation', models.CharField(max_length=255, verbose_name='Təyinat')),
                ('photo', models.ImageField(upload_to='photos/teams')),
                ('facebook_link', models.CharField(max_length=500, verbose_name='Facebook')),
                ('instagram_link', models.CharField(max_length=500, verbose_name='Instagram')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
