# Generated by Django 3.2.7 on 2021-09-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Komanda Heyyəti', 'verbose_name_plural': 'Komanda Üzvləri'},
        ),
    ]
